[package]
name = "cppcheck_crash_finder"
version = "0.1.0"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]

[dependencies]
walkdir = "2.1"
rayon = "1.0"

[profile.release]
codegen-units=1
lto=true
opt-level=3
